volumes:
  redis-data:
  postgres-data:

services:
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      # expose port 6378 to the host,
      # so that we can connect to it from
      # outside wihout interfering with
      # the host's redis
      - "6378:6379"
  postgres:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      # 5432 is the default port for postgres,
      # but we use 5442 here to avoid conflicts
      # with a local postgres installation on the host
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
